feat: cria novos componentes utilizados na modal de cep
ConsultaRemedios/cr-ui pull request #103
Opened 2022-01-19 14:36 UTC by lenonfelippi

### Descrição
Neste PR são migrados alguns componentes utilizados na Modal de CEP no porta, para o CR-UI.

task: [URL DA TASK](https://sprints.zoho.com/team/consultaremedios#itemdetails/P21/I413)

------------------------------------------------------------

### Screenshots

![image](https://user-images.githubusercontent.com/65905199/150151908-fe8703e5-1685-4d54-8001-84633729eb9a.png)

2022-01-20 12:36 UTC, Pedro-Souza commented on src/components/common/AddressList/AddressList.vue
> +        >
será que usar `ul` e `li` aqui não seria melhor? já que é uma lista?

2022-01-20 12:36 UTC, Pedro-Souza commented on src/components/common/AddressList/AddressList.vue
> +      class="col-xs-12"
não entendi esse `col-xs-12` aqui, se não me engano não temos o bootstrap no cr-ui.

2022-01-20 12:38 UTC, Pedro-Souza commented on src/components/common/AddressList/AddressList.vue
> +  mixins: [breakpointable],
esse mixin ta sendo usado? pelo que percebi recebemos por prop se é mobile ou não.

2022-01-20 12:39 UTC, Pedro-Souza commented on src/components/common/AddressList/AddressList.vue
> +    transform: rotate(45deg);
pq esses 3 rotate?

2022-01-20 12:40 UTC, Pedro-Souza commented on src/components/common/AddressList/AddressList.vue
> +  }
essas classes parece que não estão sendo utilizadas

2022-01-20 12:48 UTC, Pedro-Souza commented on src/components/common/ZipcodeForm/ZipcodeForm.vue
> +import VMasker from 'vanilla-masker';
a gente tem isso aq no cr-ui?

2022-01-20 12:48 UTC, Pedro-Souza commented on src/components/common/ZipcodeForm/ZipcodeForm.vue
> +            console.log(error.message);
e esse console aqui?

2022-01-20 12:49 UTC, Pedro-Souza commented on src/components/common/ZipcodeForm/ZipcodeForm.vue
> +          number: '',
a gente tem q mandar o zipcode e number tbm não?

2022-01-20 13:04 UTC, lenonfelippi commented on src/components/common/ZipcodeForm/ZipcodeForm.vue
> +import VMasker from 'vanilla-masker';
Tem sim:
![image](https://user-images.githubusercontent.com/65905199/150344108-06e9bd8e-d0fc-46a0-aa53-3a0b5559c9e7.png)

2022-01-20 13:10 UTC, Pedro-Souza commented on src/components/common/ZipcodeForm/ZipcodeForm.vue
> +  .findZipcodeButton :global(span) {
não entendi isso aqui, pq desse global?

2022-01-20 13:12 UTC, lenonfelippi commented on src/components/common/AddressList/AddressList.vue
> +  }
Boa! To encontrando outras class que não são utilizadas tambem.

2022-01-20 13:12 UTC, Pedro-Souza requested changes
Eu acredito que esses 2 components estão muito ligados ao CR, talvez o mais correto seria colocar eles dentro da pasta `cr`. Também faltou documentar eles, para aparecer o styleguide como usar e etc.

Fora isso, fiz alguns comentários menores.

2022-01-20 13:13 UTC, Pedro-Souza commented on src/components/common/AddressList/AddressList.vue
> +      class="col-xs-12"
no outro component tbm tem o uso de `col-xs-12` e `row` já da uma olhada nele tbem

2022-01-26 17:33 UTC, lenonfelippi commented on src/components/common/AddressList/AddressList.vue
> +        >
esse componente foi excluido e criado outro em seu lugar https://github.com/ConsultaRemedios/cr-ui/pull/103/commits/b144a2b369dec99c36b511e973ea87ad096c5a3e

2022-01-26 17:33 UTC, lenonfelippi commented on src/components/common/AddressList/AddressList.vue
> +      class="col-xs-12"
esse componente foi excluido e criado outro em seu lugar https://github.com/ConsultaRemedios/cr-ui/pull/103/commits/b144a2b369dec99c36b511e973ea87ad096c5a3e

2022-01-26 17:34 UTC, lenonfelippi commented on src/components/common/AddressList/AddressList.vue
> +  mixins: [breakpointable],
esse componente foi excluido e criado outro em seu lugar https://github.com/ConsultaRemedios/cr-ui/pull/103/commits/b144a2b369dec99c36b511e973ea87ad096c5a3e

2022-01-26 17:34 UTC, lenonfelippi commented on src/components/common/AddressList/AddressList.vue
> +    transform: rotate(45deg);
esse componente foi excluido e criado outro em seu lugar https://github.com/ConsultaRemedios/cr-ui/pull/103/commits/b144a2b369dec99c36b511e973ea87ad096c5a3e

2022-01-26 17:34 UTC, lenonfelippi commented on src/components/common/AddressList/AddressList.vue
> +  }
esse componente foi excluido e criado outro em seu lugar https://github.com/ConsultaRemedios/cr-ui/pull/103/commits/b144a2b369dec99c36b511e973ea87ad096c5a3e

2022-01-26 17:37 UTC, lenonfelippi commented on src/components/common/ZipcodeForm/ZipcodeForm.vue
> +  .findZipcodeButton :global(span) {
Fiz alguns testes e não precisava desse :global
alterei aqui https://github.com/ConsultaRemedios/cr-ui/pull/103/commits/b144a2b369dec99c36b511e973ea87ad096c5a3e

2022-01-26 17:37 UTC, lenonfelippi commented on src/components/common/ZipcodeForm/ZipcodeForm.vue
> +          number: '',
alterei aqui https://github.com/ConsultaRemedios/cr-ui/pull/103/commits/b144a2b369dec99c36b511e973ea87ad096c5a3e

2022-01-26 17:37 UTC, lenonfelippi commented on src/components/common/ZipcodeForm/ZipcodeForm.vue
> +            console.log(error.message);
alterei aqui https://github.com/ConsultaRemedios/cr-ui/pull/103/commits/b144a2b369dec99c36b511e973ea87ad096c5a3e

2022-01-27 17:38 UTC, Pedro-Souza commented on src/components/common/CardRadioButton/CardRadioButton.spec.js
> +  describe('Behavior', () => {
acho que faltou um it para testar quando o emit não é disparado.

2022-01-27 17:39 UTC, Pedro-Souza commented on src/components/cr/ZipcodeForm/ZipcodeForm.md
> +      <p>Testando</p>
da pra remover esse `p` né?

2022-01-27 17:45 UTC, Pedro-Souza commented on src/components/cr/ZipcodeForm/ZipcodeForm.vue
> +    },
Eu não entendi a lógica desse método. Me parece que os emits são sempre os mesmos. Fazer assim não seria melhor? 

```js
  if (this.zipcodeValue.length < 9) return;

  this.$emit('search', {
      zipcode: this.zipcodeValue,
      number: this.numberValue,
      lat: this.lat,
      lng: this.lng,
  });

```

2022-01-27 17:59 UTC, Pedro-Souza commented on src/components/cr/ZipcodeForm/ZipcodeForm.vue
> +    },
Ah, acho que entendi, caso tenha lat e lng pode fazer o emit mesmo se o zipcode estiver incompleto? Nesse caso eu teria feito algo +/- assim:

```js
onClickSubmit() {
  const invalidZipcode = this.zipcodeValue.length < 9;
  const hasGeolocation = this.lat && this.lng;

  if (!hasGeolocation && invalidZipcode) return; 

  this.$emit('search', {
    zipcode: this.zipcodeValue,
    number: this.numberValue,
    lat: this.lat,
    lng: this.lng,
  });
}
```

2022-01-31 10:19 UTC, lenonfelippi commented on src/components/cr/ZipcodeForm/ZipcodeForm.vue
> +    },
Fiz algumas alterações aqui https://github.com/ConsultaRemedios/cr-ui/pull/103/commits/c137e870acc4401374d81f2582aa1f1808df2fba

2022-01-31 10:19 UTC, lenonfelippi commented on src/components/cr/ZipcodeForm/ZipcodeForm.md
> +      <p>Testando</p>
boa! Removi aqui https://github.com/ConsultaRemedios/cr-ui/pull/103/commits/c137e870acc4401374d81f2582aa1f1808df2fba

2022-01-31 10:37 UTC, lenonfelippi commented on src/components/common/CardRadioButton/CardRadioButton.spec.js
> +  describe('Behavior', () => {
adicionei um teste aqui https://github.com/ConsultaRemedios/cr-ui/pull/103/commits/f2693d1e2229e9df6b562f68a74a15d8c25d7691

2022-01-31 18:10 UTC, Pedro-Souza approved these changes
:tada:

2022-02-01 20:17 UTC, JoaoMarcelo-J approved these changes

2022-02-02 16:55 UTC, merged